dist: focal
sudo: required

language: c

compiler:
- gcc

install:
- sudo apt-get install valgrind
- sudo pip3 install cpplint
- sudo apt install cppcheck

script:
- mkdir iz1/cmake-build-debug && cd iz1/cmake-build-debug/
- cmake ..
- make clean && make 
