dist: focal
sudo: required

language: c

compiler:
- gcc

install:
- sudo apt-get install valgrind
- sudo pip3 install cpplint
- sudo apt install cppcheck

script:
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
- cmake --build .
- ctest --output-on-failure
